name: miniconda3

channels:
  - conda-forge
  - nodefaults

dependencies:
  - mamba
  - conda
  - cmake
  - flex
  - bison
  - compilers
  - openmpi=4
  - compilers
  - gsl
  - pyaml
  - ply
  - matplotlib
  - numpy
  - scipy
  - tornado
  - scipy
  - pillow
  - pyqtgraph
  - pyqt
  - qtpy
  - qscintilla2
  - nexusformat
  - nexpy
  - hdf5
  - xraylib
  - mcpl
  - mcxtrace
  - jupytext
  - jupyterlab
  - ipympl
  - jinja2
  - mslex
  - nodejs
  - McStasScript
  - pip

